name: Continuous Delivery (Bindings for Azure Functions 2.x+ Isolated Worker Model)
on:
  push:
    tags:
    - "azurefunctions-isolated-worker-v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-test-pack-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Extract VERSION
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/azurefunctions-isolated-worker-v/}" >> $GITHUB_ENV
      shell: bash
    - name: Setup .NET 6.0 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
    - name: Restore
      run: dotnet restore src/RethinkDb.Azure.Functions.Worker.Extensions
    - name: Build
      run: dotnet build src/RethinkDb.Azure.Functions.Worker.Extensions --configuration Release --no-restore
    - name: Pack
      run: dotnet pack src/RethinkDb.Azure.Functions.Worker.Extensions --configuration Release --no-build
    - name: NuGet Push RethinkDb.Azure.Functions.Worker.Extensions
      run: dotnet nuget push src/RethinkDb.Azure.Functions.Worker.Extensions/bin/Release/RethinkDb.Azure.Functions.Worker.Extensions.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      shell: bash
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}